var a=1;
var b=5;
var c=6;
 var root_part=Math.sqrt(b*b-4*a*c);
  var denom=2*a;
var root1=(-b+root_part)/denom;
  var root2=(-b-root_part)/denom;
console.log("1st root:",root1);
   console.log("2nd root:",root2);;